package com.jinlong.model;

public class JProduct {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product.content
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product.name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product.picture
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product.p_id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private Integer pId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product.id
     *
     * @return the value of j_product.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product.id
     *
     * @param id the value for j_product.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product.content
     *
     * @return the value of j_product.content
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product.content
     *
     * @param content the value for j_product.content
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product.name
     *
     * @return the value of j_product.name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product.name
     *
     * @param name the value for j_product.name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product.picture
     *
     * @return the value of j_product.picture
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product.picture
     *
     * @param picture the value for j_product.picture
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product.p_id
     *
     * @return the value of j_product.p_id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public Integer getpId() {
        return pId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product.p_id
     *
     * @param pId the value for j_product.p_id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setpId(Integer pId) {
        this.pId = pId;
    }
}