package com.jinlong.model;

public class JProductSet {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product_set.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product_set.name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column j_product_set.url
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product_set.id
     *
     * @return the value of j_product_set.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product_set.id
     *
     * @param id the value for j_product_set.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product_set.name
     *
     * @return the value of j_product_set.name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product_set.name
     *
     * @param name the value for j_product_set.name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column j_product_set.url
     *
     * @return the value of j_product_set.url
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column j_product_set.url
     *
     * @param url the value for j_product_set.url
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setUrl(String url) {
        this.url = url;
    }
}