package com.jinlong.model;

import java.util.List;

public class T1Model {
	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t1_model.id
	 *
	 * @mbg.generated Tue Jan 30 21:27:03 CST 2018
	 */
	private Integer id;

	/**
	 *
	 * This field was generated by MyBatis Generator. This field corresponds to the
	 * database column t1_model.name
	 *
	 * @mbg.generated Tue Jan 30 21:27:03 CST 2018
	 */
	private String name;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t1_model.id
	 *
	 * @return the value of t1_model.id
	 *
	 * @mbg.generated Tue Jan 30 21:27:03 CST 2018
	 */
	
	private Integer pid;
	
	private Integer funId;
	
	private List<T1Fun> funList;

	private String url;
	
	private List<T1Model> childModel;
	
	
	public Integer getPid() {
		return pid;
	}

	public void setPid(Integer pid) {
		this.pid = pid;
	}
	
	public Integer getFunId() {
		return funId;
	}

	public void setFunId(Integer funId) {
		this.funId = funId;
	}

	public List<T1Model> getChildModel() {
		return childModel;
	}

	public void setChildModel(List<T1Model> childModel) {
		this.childModel = childModel;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public List<T1Fun> getFunList() {
		return funList;
	}

	public void setFunList(List<T1Fun> funList) {
		this.funList = funList;
	}

	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t1_model.id
	 *
	 * @param id
	 *            the value for t1_model.id
	 *
	 * @mbg.generated Tue Jan 30 21:27:03 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value
	 * of the database column t1_model.name
	 *
	 * @return the value of t1_model.name
	 *
	 * @mbg.generated Tue Jan 30 21:27:03 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of
	 * the database column t1_model.name
	 *
	 * @param name
	 *            the value for t1_model.name
	 *
	 * @mbg.generated Tue Jan 30 21:27:03 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	@Override
	public String toString() {
		return "T1Model [id=" + id + ", name=" + name + ", pid=" + pid + ", funId=" + funId + ", funList=" + funList
				+ ", url=" + url + ", childModel=" + childModel + "]";
	}
	
	
}