package com.jinlong.model;

public class T1Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1_role.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t1_role.r_name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    private String rName;
    
    
    
    private String rIds;
    
    private String rNames;

    
    public String getrIds() {
		return rIds;
	}

	public void setrIds(String rIds) {
		this.rIds = rIds;
	}

	public String getrNames() {
		return rNames;
	}

	public void setrNames(String rNames) {
		this.rNames = rNames;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1_role.id
     *
     * @return the value of t1_role.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1_role.id
     *
     * @param id the value for t1_role.id
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t1_role.r_name
     *
     * @return the value of t1_role.r_name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t1_role.r_name
     *
     * @param rName the value for t1_role.r_name
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    public void setrName(String rName) {
        this.rName = rName;
    }
}