package com.jinlong.mapper;

import com.jinlong.model.JProduct;
import com.jinlong.model.JProductExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JProductMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    long countByExample(JProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByExample(JProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insert(JProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insertSelective(JProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    List<JProduct> selectByExample(JProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    JProduct selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") JProduct record, @Param("example") JProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExample(@Param("record") JProduct record, @Param("example") JProductExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKeySelective(JProduct record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKey(JProduct record);
}