package com.jinlong.mapper;

import com.jinlong.model.JProductSet;
import com.jinlong.model.JProductSetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface JProductSetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    long countByExample(JProductSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByExample(JProductSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insert(JProductSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insertSelective(JProductSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    List<JProductSet> selectByExample(JProductSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    JProductSet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") JProductSet record, @Param("example") JProductSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExample(@Param("record") JProductSet record, @Param("example") JProductSetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKeySelective(JProductSet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table j_product_set
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKey(JProductSet record);
}