package com.jinlong.mapper;

import com.jinlong.model.T1Fun;
import com.jinlong.model.T1FunExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T1FunMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    long countByExample(T1FunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByExample(T1FunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insert(T1Fun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insertSelective(T1Fun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    List<T1Fun> selectByExample(T1FunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    T1Fun selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") T1Fun record, @Param("example") T1FunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExample(@Param("record") T1Fun record, @Param("example") T1FunExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKeySelective(T1Fun record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_fun
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKey(T1Fun record);

	List<T1Fun> getFunBymoduleIdList(Integer modelId);
}