package com.jinlong.mapper;

import com.jinlong.model.T1Model;
import com.jinlong.model.T1ModelExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T1ModelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    long countByExample(T1ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByExample(T1ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insert(T1Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insertSelective(T1Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    List<T1Model> selectByExample(T1ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    T1Model selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") T1Model record, @Param("example") T1ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExample(@Param("record") T1Model record, @Param("example") T1ModelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKeySelective(T1Model record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_model
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKey(T1Model record);
    
    List<T1Model> getModelList(Integer userId);
    
    
	List<T1Model> getPermitByRoleId(Integer roleId);

	List<T1Model> getChildList(Integer pid);
}