package com.jinlong.mapper;

import com.jinlong.model.T1Role;
import com.jinlong.model.T1RoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T1RoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    long countByExample(T1RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByExample(T1RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insert(T1Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insertSelective(T1Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    List<T1Role> selectByExample(T1RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    T1Role selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") T1Role record, @Param("example") T1RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExample(@Param("record") T1Role record, @Param("example") T1RoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKeySelective(T1Role record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_role
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKey(T1Role record);
    
    

	Integer getModelFunId(@Param("modelId") Integer modelId,@Param("funId") Integer funId);
    
    
}