package com.jinlong.mapper;

import com.jinlong.model.T1Fun;
import com.jinlong.model.T1Model;
import com.jinlong.model.T1Role;
import com.jinlong.model.T1User;
import com.jinlong.model.T1UserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface T1UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    long countByExample(T1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByExample(T1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insert(T1User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int insertSelective(T1User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    List<T1User> selectByExample(T1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    T1User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") T1User record, @Param("example") T1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByExample(@Param("record") T1User record, @Param("example") T1UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKeySelective(T1User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t1_user
     *
     * @mbg.generated Tue Jan 30 21:27:03 CST 2018
     */
    int updateByPrimaryKey(T1User record);

	T1User getUserByValue(String username);

	
}